---
title: "SUICIDE STATISTICS BY EDUCATIONAL LEVEL IN TURKEY"
author: 
  - Kul, Sılanur Ayşen[^1]
bibliography: ../bibliography/biblio.bib
csl: ../csl/apa.csl
header-includes:
  - \usepackage{polyglossia}
  - \setmainlanguage{english}
  - \usepackage{booktabs}
  - \usepackage{caption} 
  - \captionsetup[table]{skip=10pt}
output:
  bookdown::pdf_document2:
    fig_caption: yes
    fig_height: 3
    fig_width: 4
    keep_tex: no
    latex_engine: xelatex
    number_sections: yes
    toc: no
geometry: margin=1in
link-citations: yes
urlcolor: blue
fontsize: 12pt
biblio-style: apalike
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(cache = FALSE, echo = TRUE, message = FALSE, warning = FALSE)
```

<!-- ======================================================================= -->
<!-- ============================== FOOTNOTES ============================== -->
<!-- ======================================================================= -->
[^1]: 19080406, [Github Repo](https://github.com/silakul/midterm)

# Important Information About Midterm

\colorbox{BurntOrange}{WRITE YOUR GITHUB REPO LINK ON LINE 35 IN THIS FILE!}

**Project Proposal submisson will be done by uploading a zip file to the ekampus system along with the Github repo link. If you do not upload a zip file to the system and do not provide a Github repo link, you will be deemed not to have entered the midterm and final exams.**

**You must upload your project folder (`YourStudentID.zip` file) to *ekampus.ankara.edu.tr* until 16 April 2023, 23:59.**

\colorbox{WildStrawberry}{Read the README.md file in the project folder for more information.}

# Introduction
Today, suicide is a global problem that concerns many countries, including Turkey. According to the Turkish Statistical Institute (TUIK), 3,755 people died by suicide in Turkey in 2019, and 70.7% of the cases were men. Suicide is a psychological issue and can occur for different reasons. However, studies suggest that education level may be one of the factors affecting suicide rates.

There is an inverse correlation between education level and suicide rates in Turkey. According to the previously mentioned TUIK report, people with higher levels of education have a lower risk of suicide. While the suicide rate is 31.7% for those with primary school education and below, it is 7.5% for those with higher education. This statistic is in line with studies conducted in other countries that show that education level is inversely proportional to suicide rates.

One of the few reasons why education level influences suicide rates is that education has an impact on mental health. For example, training can improve coping skills. Also, people with higher levels of education are more likely to have better job opportunities, higher income, and a social space where they can get away from stress and negativity.


In conclusion, education level may be a factor affecting suicide rates, and higher education levels may be associated with lower suicide rates.

## Literature Review

Suicide statistics in Turkey may vary depending on certain factors. There are research and reports made by the Turkish Statistical Institute (TUIK) on this subject. According to TURKSTAT's 2019 "Cause of Death Statistics" report, a total of 3,755 people committed suicide in Turkey in 2019, of which 70.7% were male and 29.3% were female.

If we analyze this report by education level:

Suicide cases in primary school graduates and below: 31.7%
Suicide cases among secondary school graduates: 30.3%
Suicide cases among high school graduates: 22.5%
Suicide cases among university graduates: 7.5% [@ozcan2018turkiye]

According to these data, suicide rates decrease as the level of education increases in Turkey. These statistics show that education plays an important role in people's psychological health. [@dumbrava2016relation]



**References section is created automatically by Rmarkdown. There is no need to change the references section in the draft file.**

**_You shouldn't delete the last 3 lines. Those lines are required for References section._**

\newpage
# References {#references}
<div id="refs"></div>

